// Code generated by goctl. DO NOT EDIT.
package types

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Note struct {
	ID        string `json:"id"`
	Content   []byte `json:"content"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type NoteContentResponse struct {
	Content   []byte `json:"content"`
	UpdatedAt string `json:"updatedAt"`
}

type NoteUploadRequest struct {
	FileContent []byte `form:"fileContent"` // 文件内容
	FileName    string `form:"fileName"`    // 文件名
	Timestamp   int64  `form:"timestamp"`   // 时间戳
	NoteID      int64  `form:"noteId"`      // 关联的笔记文件ID
}

type NoteUploadResponse struct {
	Base
	Data NoteUploadResponseData `json:"data"`
}

type NoteUploadResponseData struct {
	ID int64
}

type Id struct {
	ID int64 `json:"id"`
}
