// Code generated by goctl. DO NOT EDIT.
package types

type Creator struct {
	ID    int64
	Name  string
	Email string
}

type ID struct {
	ID int64
}

type NoteResp struct {
	ID      int64
	Title   string
	Content string
	FileID  int64
	Creator Creator `json:"creator"`
}
