// Code generated by goctl. DO NOT EDIT.
package types

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Id struct {
	ID int64 `json:"id"`
}

type Note struct {
	Id        string `json:"id"`
	Content   []byte `json:"content"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type NoteContentResponse struct {
	Content   []byte `json:"content"`
	UpdatedAt string `json:"updatedAt"`
}

type NoteUploadRequest struct {
	FileContent []byte // 文件内容  // 文件内容
	FileName    string // 文件名
	Timestamp   int64  // 时间戳
	NoteID      int64  // 关联的笔记文件ID
}

type NoteUploadResponse struct {
	Base
	Data noteUploadResponseData `json:"data"`
}

type NoteUploadResponseData struct {
	Id int64
}
