// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"wangzheng/brain/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取文件内容
				Method:  http.MethodGet,
				Path:    "/note/content",
				Handler: getNoteContentHandler(serverCtx),
			},
			{
				// 保存文件内容
				Method:  http.MethodPut,
				Path:    "/note/content",
				Handler: saveNoteContentHandler(serverCtx),
			},
			{
				// 上传文件
				Method:  http.MethodPost,
				Path:    "/note/upload",
				Handler: uploadNoteHandler(serverCtx),
			},
		},
	)
}
